### ISSUE TITLE
Open api qps request limit reached

### ISSUE THREAD

**Issue by zwjzxh520** [oott123/alfred-clipboard-ocr#12]
alfred版本：4.3.4[1229]

日志如下：
```
[17:29:07.745] OCR Clipboard[Keyword] Processing complete
[17:29:07.748] OCR Clipboard[Keyword] Passing output '' to Run Script
[17:29:09.722] ERROR: OCR Clipboard[Run Script] request failed, clear credentials cache and try again
Open api qps request limit reached
undefined method `stack' for #<RuntimeError: Open api qps request limit reached>
/Users/niel/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF3664E8-4156-4D68-B137-2553F6A6DDC4/ocr.rb:119:in `rescue in <main>': undefined method `stack' for #<NoMethodError:0x00007f923d955138> (NoMethodError)
	from /Users/niel/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF3664E8-4156-4D68-B137-2553F6A6DDC4/ocr.rb:90:in `<main>'
/Users/niel/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF3664E8-4156-4D68-B137-2553F6A6DDC4/ocr.rb:101:in `rescue in <main>': undefined method `stack' for #<RuntimeError: Open api qps request limit reached> (NoMethodError)
	from /Users/niel/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF3664E8-4156-4D68-B137-2553F6A6DDC4/ocr.rb:96:in `<main>'
/Users/niel/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF3664E8-4156-4D68-B137-2553F6A6DDC4/ocr.rb:71:in `ocr_text': Open api qps request limit reached (RuntimeError)
	from /Users/niel/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF3664E8-4156-4D68-B137-2553F6A6DDC4/ocr.rb:97:in `<main>'
[17:29:09.733] OCR Clipboard[Run Script] Processing complete
[17:29:09.734] OCR Clipboard[Run Script] Passing output 'something' to Post Notification
```

**Comment by oott123** [comment]
根据百度的《[公有云服务免费测试额度调整](https://ai.baidu.com/support/news?action=detail&id=2390)》公告，如果你在 2021年04月24日 ~ 2021年5月26日 没有成功调用任意一次 OCR 接口，那么你的免费额度已被收回。

收回后，在控制台可以重新[免费领取额度](https://console.bce.baidu.com/ai/#/ai/ocr/overview/resource/getFree)。领取后不需要其它操作，等待几分钟就可以生效了。

**Comment by zwjzxh520** [comment]
感谢，确实是这个原因。
刚刚登录百度云控制台，完成了实名认证，领取免费资源后，然后重启 alfred 就可以了
